### ISSUE TITLE
Windows 10 support

### ISSUE THREAD

**Issue by PhilippeVienne** [BdEINSALyon/dashboard_client#1]
Errors while running the client script on Windows 10 :

```
restart_needed False
Erreur : Le fichier spécifié est introuvable.
Erreur : Le fichier spécifié est introuvable.
Traceback (most recent call last):
  File "check_status.py", line 441, in <module>
    main()
  File "check_status.py", line 55, in main
    check_network(status)
  File "check_status.py", line 318, in check_network
    net_full = get_ret_str('netsh interface ip show config "Connexion au réseau local{0}"'.format(tag))
  File "check_status.py", line 437, in get_ret_str
    return get_ret(cmd, *args, **kwargs).decode('cp850').lower()
  File "check_status.py", line 433, in get_ret
    return subprocess.check_output(cmd, *args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Program Files (x86)\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'netsh interface ip show config "Connexion au réseau local 2"' returned non-zero exit status 1.
```

**Comment by Crocmagnon** [comment]
Quel ordinateur est affecté ?

**Comment by Crocmagnon** [comment]
Changement dans les noms d'interface réseau par Microsoft entre Win 7 et 10
